-- Script SQL para criar e popular as 3 tabelas de Recursos Humanos
-- Baseado nas planilhas fornecidas

-- ===============================================
-- 1. TABELA: RH_GASTOS_GERAIS
-- ===============================================

-- Criar tabela rh_gastos_gerais
CREATE TABLE IF NOT EXISTS rh_gastos_gerais (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    categoria TEXT NOT NULL,
    "Janeiro" NUMERIC DEFAULT 0.00,
    "Fevereiro" NUMERIC DEFAULT 0.00,
    "Marco" NUMERIC DEFAULT 0.00,
    "Abril" NUMERIC DEFAULT 0.00,
    "Maio" NUMERIC DEFAULT 0.00,
    "Junho" NUMERIC DEFAULT 0.00,
    "Julho" NUMERIC DEFAULT 0.00,
    "Agosto" NUMERIC DEFAULT 0.00,
    "Setembro" NUMERIC DEFAULT 0.00,
    "Outubro" NUMERIC DEFAULT 0.00,
    "Novembro" NUMERIC DEFAULT 0.00,
    "Dezembro" NUMERIC DEFAULT 0.00,
    "Total_Anual" NUMERIC DEFAULT 0.00,
    ano INTEGER DEFAULT EXTRACT(year FROM CURRENT_DATE)
);

-- Inserir dados em rh_gastos_gerais
INSERT INTO rh_gastos_gerais (categoria, "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", "Total_Anual", ano) VALUES
('AÇÕES TRABALHISTAS', 0.00, 0.00, 3500.00, 3500.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 7000.00, 2024),
('ADICIONAL NOTURNO', 367.92, 582.03, 591.07, 626.11, 610.12, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 2777.25, 2024),
('AJUDA DE CUSTO', 4157.14, 4867.50, 4397.14, 4690.00, 4185.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 22296.78, 2024),
('ALIMENTAÇÃO', 19371.90, 24423.88, 20200.50, 21480.02, 25088.74, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 110565.04, 2024),
('CO PARTICIPAÇÃO PLANO DE SAÚDE', 54.70, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 54.70, 2024),
('CURSOS / AUX. FACULDADE', 389.00, 602.79, 470.04, 602.79, 602.79, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 2667.41, 2024),
('CUSTOS DE RESCISÕES', 7353.04, 11819.95, 6807.47, 10533.35, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 36513.81, 2024),
('GRATIF/INDENIZ/DESCONTOS', 16576.34, 7580.74, 2233.18, 17635.11, 1266.67, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 45292.04, 2024),
('GRATIFICAÇÃO /FUNÇÃO', 4246.67, 5440.00, 11512.00, 11512.00, 5024.40, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 37735.07, 2024),
('GRATIFICAÇÃO EXTRAORDINÁRIA', 2365.08, 0.00, 201.66, 760.00, 6095.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 9421.74, 2024),
('GUIA DE FGTS MENSAL', 15613.47, 12555.28, 12448.74, 13161.87, 14617.57, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 68396.93, 2024),
('GUIA DE IRRF MENSAL', 2208.13, 3554.49, 6821.12, 6288.28, 5721.12, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 24593.14, 2024),
('GUIA INSS FUNCIONÁRIO', 15531.35, 23603.72, 9839.43, 10017.92, 11416.31, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 70408.73, 2024),
('GUIA INSS PATRONAL', 37098.92, 34185.33, 33581.38, 34274.05, 37902.02, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 177041.70, 2024),
('HORAS EXTRAS', 13754.55, 13320.67, 8283.79, 9050.56, 17560.69, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 61970.26, 2024),
('MYRH /TECNOPONTO', 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 2024),
('PLANO ODONTOLÓGICO', 516.71, 650.29, 776.35, 638.20, 929.45, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 3511.00, 2024),
('SEGURANÇA DO TRABALHO', 5669.94, 10563.10, 11477.34, 12761.03, 7111.51, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 47582.92, 2024),
('SEG DO TRABALHO ECO SALVA', 628.12, 615.87, 593.12, 697.67, 629.50, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 3164.28, 2024),
('SEGURO FUNCIONÁRIOS', 1037.28, 1039.23, 1156.79, 1452.67, 1464.72, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 6150.69, 2024),
('SINDIMETAL/SINDICATO/PATRONAL', 0.00, 346.00, 635.00, 346.00, 346.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1673.00, 2024),
('UNIFORME', 1414.00, 159.80, 0.00, 6470.70, 3861.79, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 11906.29, 2024),
('VALE TRANSPORTE', 1901.41, 2571.72, 2331.05, 2434.30, 3267.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 12505.53, 2024);

-- ===============================================
-- 2. TABELA: RH_CUSTOS_TOTAIS
-- ===============================================

-- Criar tabela rh_custos_totais
CREATE TABLE IF NOT EXISTS rh_custos_totais (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    categoria TEXT NOT NULL,
    "Janeiro" NUMERIC DEFAULT 0.00,
    "Fevereiro" NUMERIC DEFAULT 0.00,
    "Marco" NUMERIC DEFAULT 0.00,
    "Abril" NUMERIC DEFAULT 0.00,
    "Maio" NUMERIC DEFAULT 0.00,
    "Junho" NUMERIC DEFAULT 0.00,
    "Julho" NUMERIC DEFAULT 0.00,
    "Agosto" NUMERIC DEFAULT 0.00,
    "Setembro" NUMERIC DEFAULT 0.00,
    "Outubro" NUMERIC DEFAULT 0.00,
    "Novembro" NUMERIC DEFAULT 0.00,
    "Dezembro" NUMERIC DEFAULT 0.00,
    "Total_Anual" NUMERIC DEFAULT 0.00,
    ano INTEGER DEFAULT EXTRACT(year FROM CURRENT_DATE)
);

-- Inserir dados em rh_custos_totais
INSERT INTO rh_custos_totais (categoria, "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", "Total_Anual", ano) VALUES
('GASTOS GERAIS', 147323.89, 156399.95, 134216.69, 165648.28, 147700.45, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 751289.27, 2024),
('FÉRIAS/REFLEXOS', 3847.83, 4228.39, 6439.22, 6372.56, 4349.22, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 25237.22, 2024),
('13º/REFLEXOS', 11543.50, 12685.17, 12740.53, 12510.17, 13047.67, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 62527.04, 2024),
('FGTS/REFLEXOS', 1231.31, 1353.08, 1507.95, 1510.62, 1391.75, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 6994.71, 2024),
('SALÁRIOS', 178884.75, 184209.42, 166413.58, 167613.58, 190133.13, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 887254.46, 2024);

-- ===============================================
-- 3. TABELA: RH_PASSIVO_TRABALHISTA
-- ===============================================

-- Criar tabela rh_passivo_trabalhista
CREATE TABLE IF NOT EXISTS rh_passivo_trabalhista (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    categoria TEXT NOT NULL,
    "Janeiro" NUMERIC DEFAULT 0.00,
    "Fevereiro" NUMERIC DEFAULT 0.00,
    "Marco" NUMERIC DEFAULT 0.00,
    "Abril" NUMERIC DEFAULT 0.00,
    "Maio" NUMERIC DEFAULT 0.00,
    "Junho" NUMERIC DEFAULT 0.00,
    "Julho" NUMERIC DEFAULT 0.00,
    "Agosto" NUMERIC DEFAULT 0.00,
    "Setembro" NUMERIC DEFAULT 0.00,
    "Outubro" NUMERIC DEFAULT 0.00,
    "Novembro" NUMERIC DEFAULT 0.00,
    "Dezembro" NUMERIC DEFAULT 0.00,
    "Total_Anual" NUMERIC DEFAULT 0.00,
    ano INTEGER DEFAULT EXTRACT(year FROM CURRENT_DATE)
);

-- Inserir dados em rh_passivo_trabalhista
INSERT INTO rh_passivo_trabalhista (categoria, "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", "Total_Anual", ano) VALUES
('PASSIVO TRABALHISTA CONTABILIDADE', 582929.13, 472630.81, 525403.37, 705510.82, 735531.26, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 3022005.39, 2024); 