-- Script SQL para criar e popular a tabela RH_CUSTOS_TOTAIS
-- Baseado nos dados da planilha "CUSTOS TOTAIS MENSAIS COM OS COLABORADORES"

-- ===============================================
-- CRIAR TABELA RH_CUSTOS_TOTAIS
-- ===============================================

CREATE TABLE IF NOT EXISTS rh_custos_totais (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    categoria TEXT NOT NULL,
    "Janeiro" NUMERIC DEFAULT 0.00,
    "Fevereiro" NUMERIC DEFAULT 0.00,
    "Marco" NUMERIC DEFAULT 0.00,
    "Abril" NUMERIC DEFAULT 0.00,
    "Maio" NUMERIC DEFAULT 0.00,
    "Junho" NUMERIC DEFAULT 0.00,
    "Julho" NUMERIC DEFAULT 0.00,
    "Agosto" NUMERIC DEFAULT 0.00,
    "Setembro" NUMERIC DEFAULT 0.00,
    "Outubro" NUMERIC DEFAULT 0.00,
    "Novembro" NUMERIC DEFAULT 0.00,
    "Dezembro" NUMERIC DEFAULT 0.00,
    "Total_Anual" NUMERIC DEFAULT 0.00,
    ano INTEGER DEFAULT EXTRACT(year FROM CURRENT_DATE)
);

-- ===============================================
-- INSERIR DADOS EM RH_CUSTOS_TOTAIS
-- ===============================================

INSERT INTO rh_custos_totais (categoria, "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", "Total_Anual", ano) VALUES
('GASTOS GERAIS', 147323.89, 156399.95, 134216.69, 165648.28, 147700.45, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 751289.27, 2024),
('FÉRIAS/REFLEXOS', 3847.83, 4228.39, 6439.22, 6372.56, 4349.22, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 25237.22, 2024),
('13º/REFLEXOS', 11543.50, 12685.17, 12740.53, 12510.17, 13047.67, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 62527.04, 2024),
('FGTS/REFLEXOS', 1231.31, 1353.08, 1507.95, 1510.62, 1391.75, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 6994.71, 2024),
('SALÁRIOS', 178884.75, 184209.42, 166413.58, 167613.58, 190133.13, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 887254.46, 2024);

-- ===============================================
-- VERIFICAR INSERÇÃO
-- ===============================================

-- Para verificar se os dados foram inseridos corretamente:
-- SELECT categoria, "Total_Anual" FROM rh_custos_totais ORDER BY "Total_Anual" DESC;

-- Para verificar os totais mensais:
-- SELECT 
--   'TOTAL MENSAL' as categoria,
--   SUM("Janeiro") as "Janeiro",
--   SUM("Fevereiro") as "Fevereiro", 
--   SUM("Marco") as "Marco",
--   SUM("Abril") as "Abril",
--   SUM("Maio") as "Maio",
--   SUM("Total_Anual") as "Total_Anual"
-- FROM rh_custos_totais; 