-- Script SQL para criar e popular a tabela RH_PASSIVO_TRABALHISTA
-- Baseado nos dados da planilha "PASSIVO TRABALHISTA USIFIX"

-- ===============================================
-- CRIAR TABELA RH_PASSIVO_TRABALHISTA
-- ===============================================

CREATE TABLE IF NOT EXISTS rh_passivo_trabalhista (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    categoria TEXT NOT NULL,
    "Janeiro" NUMERIC DEFAULT 0.00,
    "Fevereiro" NUMERIC DEFAULT 0.00,
    "Marco" NUMERIC DEFAULT 0.00,
    "Abril" NUMERIC DEFAULT 0.00,
    "Maio" NUMERIC DEFAULT 0.00,
    "Junho" NUMERIC DEFAULT 0.00,
    "Julho" NUMERIC DEFAULT 0.00,
    "Agosto" NUMERIC DEFAULT 0.00,
    "Setembro" NUMERIC DEFAULT 0.00,
    "Outubro" NUMERIC DEFAULT 0.00,
    "Novembro" NUMERIC DEFAULT 0.00,
    "Dezembro" NUMERIC DEFAULT 0.00,
    "Total_Anual" NUMERIC DEFAULT 0.00,
    ano INTEGER DEFAULT EXTRACT(year FROM CURRENT_DATE)
);

-- ===============================================
-- INSERIR DADOS EM RH_PASSIVO_TRABALHISTA
-- ===============================================

INSERT INTO rh_passivo_trabalhista (categoria, "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", "Total_Anual", ano) VALUES
('PASSIVO TRABALHISTA CONTABILIDADE', 582929.13, 472630.81, 525403.37, 705510.82, 735531.26, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 3022005.39, 2024);

-- ===============================================
-- VERIFICAR INSERÇÃO
-- ===============================================

-- Para verificar se os dados foram inseridos corretamente:
-- SELECT categoria, "Total_Anual" FROM rh_passivo_trabalhista ORDER BY "Total_Anual" DESC;

-- Para verificar os valores mensais:
-- SELECT 
--   categoria,
--   "Janeiro", "Fevereiro", "Marco", "Abril", "Maio",
--   "Total_Anual"
-- FROM rh_passivo_trabalhista;

-- Para calcular a soma dos primeiros 5 meses:
-- SELECT 
--   categoria,
--   ("Janeiro" + "Fevereiro" + "Marco" + "Abril" + "Maio") as "Soma_5_Meses",
--   "Total_Anual"
-- FROM rh_passivo_trabalhista; 